	INC =
	LIB =

#================= GUROBI =====================================================
VERSION := $(shell gurobi_cl --version | cut -c 26,28,30 | head -n 1)
FLAGVERSION := $(shell gurobi_cl --version | cut -c 26,28 | head -n 1)

ifeq ($(shell uname), Darwin)
	PLATFORM = mac64
	CC      = g++
	CC_ARGS    = -Wall -m64 -stdlib=libstdc++ -O3 -Wall -std=c++11
	RELEASE := $(shell uname -r | cut -f 1 -d .)
	CC_LIB   = -lm -lpthread
	ifneq ($(RELEASE), 11)
		CPPSTDLIB = -stdlib=libstdc++
	endif
	GUROBI_DIR = /Library/gurobi$(VERSION)/$(PLATFORM)

else
	PLATFORM = linux64
	CC      = g++
	CC_ARGS    = -m64 -O2 -Wall -std=c++11
	#CC_ARGS    = -m64 -O2 -Wall -std=c++0x
	RELEASE := $(shell uname -r | cut -f 1 -d .)
	CC_LIB   = -lm -lpthread
	GUROBI_DIR = /opt/gurobi$(VERSION)/$(PLATFORM)/
endif
GUROBI_INC = -I$(GUROBI_DIR)/include/
GUROBI_LIB = -L$(GUROBI_DIR)/lib/  -lgurobi_c++ -lgurobi$(FLAGVERSION)  $(CPPSTDLIB)
#================= GUROBI =====================================================

#LEMONDIR  = $(shell pwd)/../lemon/lemon-1.3.1
#LEMONINCDIR  = -I$(LEMONDIR)/include
#LEMONLIBDIR  = -L$(LEMONDIR)/lib
#---------------------------------------------
# define includes and libraries
INC = $(GUROBI_INC)  $(LEMONINCDIR)
LIB = $(CC_LIB) $(GUROBI_LIB)  $(LEMONLIBDIR)

EX = alocacao_propaganda.cpp gera_entradas.cpp

OBJEX = $(EX:.cpp=.o)

EXE = $(EX:.cpp=.e)

all: $(OBJEX) $(EXE)

mylib.a: $(MYOBJLIB)
	#libtool -o $@ $(MYOBJLIB)
	ar cru $@ $(MYOBJLIB)

%.o: %.cpp 
	$(CC) $(CC_ARGS) -c $^ $(INC) -o $@  

%.e: %.o 
	$(CC) $(CC_ARGS) $^  -o $@ $(LIB) 

.cpp.o:
	$(CC) -c $(CARGS) $< -o $@

clean:
	rm -f $(OBJ) $(EXE) $(OBJEX) *~ core
